// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhainonDistributionCenter;

#nullable disable

namespace PhainonDistributionCenter.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20250920014135_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DistributionChannelDistributionInfo", b =>
                {
                    b.Property<Guid>("AssociatedDistributionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelsId")
                        .HasColumnType("uuid");

                    b.HasKey("AssociatedDistributionsId", "ChannelsId");

                    b.HasIndex("ChannelsId");

                    b.ToTable("DistributionChannelDistributionInfo");
                });

            modelBuilder.Entity("PhainonDistributionCenter.Entities.DistributionChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DistributionChannels");
                });

            modelBuilder.Entity("PhainonDistributionCenter.Entities.DistributionInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeLog")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("VersionInfoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VersionInfoId");

                    b.ToTable("DistributionInfos");
                });

            modelBuilder.Entity("PhainonDistributionCenter.Entities.DistributionSubChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Arch")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("BuildType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DistributionInfoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FileMapInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Os")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Package")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DistributionInfoId");

                    b.HasIndex("FileMapInfoId");

                    b.ToTable("DistributionSubChannels");
                });

            modelBuilder.Entity("PhainonDistributionCenter.Entities.FileMapInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PgpSignature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PublicKeyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PublicKeyId");

                    b.ToTable("FileMapInfos");
                });

            modelBuilder.Entity("PhainonDistributionCenter.Entities.FileRepoEntry", b =>
                {
                    b.Property<byte[]>("FileSha512")
                        .HasMaxLength(64)
                        .HasColumnType("bytea");

                    b.Property<string>("ArchiveDownloadUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("ArchiveSha512")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FileSha512");

                    b.ToTable("FileRepoEntries");
                });

            modelBuilder.Entity("PhainonDistributionCenter.Entities.GpgPublicKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("KeyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("KeyId");

                    b.ToTable("PublicKeys");
                });

            modelBuilder.Entity("PhainonDistributionCenter.Entities.VersionInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codename")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("VersionInfos");
                });

            modelBuilder.Entity("DistributionChannelDistributionInfo", b =>
                {
                    b.HasOne("PhainonDistributionCenter.Entities.DistributionInfo", null)
                        .WithMany()
                        .HasForeignKey("AssociatedDistributionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhainonDistributionCenter.Entities.DistributionChannel", null)
                        .WithMany()
                        .HasForeignKey("ChannelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhainonDistributionCenter.Entities.DistributionInfo", b =>
                {
                    b.HasOne("PhainonDistributionCenter.Entities.VersionInfo", "VersionInfo")
                        .WithMany()
                        .HasForeignKey("VersionInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VersionInfo");
                });

            modelBuilder.Entity("PhainonDistributionCenter.Entities.DistributionSubChannel", b =>
                {
                    b.HasOne("PhainonDistributionCenter.Entities.DistributionInfo", "DistributionInfo")
                        .WithMany("SubChannels")
                        .HasForeignKey("DistributionInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhainonDistributionCenter.Entities.FileMapInfo", "FileMapInfo")
                        .WithMany()
                        .HasForeignKey("FileMapInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DistributionInfo");

                    b.Navigation("FileMapInfo");
                });

            modelBuilder.Entity("PhainonDistributionCenter.Entities.FileMapInfo", b =>
                {
                    b.HasOne("PhainonDistributionCenter.Entities.GpgPublicKey", "PublicKey")
                        .WithMany()
                        .HasForeignKey("PublicKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PublicKey");
                });

            modelBuilder.Entity("PhainonDistributionCenter.Entities.DistributionInfo", b =>
                {
                    b.Navigation("SubChannels");
                });
#pragma warning restore 612, 618
        }
    }
}
