// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhainonDistributionCenter;

#nullable disable

namespace PhainonDistributionCenter.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20250729031652_AddChangeLogsProperty")]
    partial class AddChangeLogsProperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DistributionChannelDistributionInfo", b =>
                {
                    b.Property<Guid>("AssociatedDistributionsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChannelsId")
                        .HasColumnType("char(36)");

                    b.HasKey("AssociatedDistributionsId", "ChannelsId");

                    b.HasIndex("ChannelsId");

                    b.ToTable("DistributionChannelDistributionInfo");
                });

            modelBuilder.Entity("PhainonDistributionCenter.Entities.DistributionChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("DistributionChannels");
                });

            modelBuilder.Entity("PhainonDistributionCenter.Entities.DistributionInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ChangeLog")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("VersionInfoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("VersionInfoId");

                    b.ToTable("DistributionInfos");
                });

            modelBuilder.Entity("PhainonDistributionCenter.Entities.DistributionSubChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Arch")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("BuildType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DistributionInfoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FileMapInfoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Os")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Package")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DistributionInfoId");

                    b.HasIndex("FileMapInfoId");

                    b.ToTable("DistributionSubChannels");
                });

            modelBuilder.Entity("PhainonDistributionCenter.Entities.FileMapInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PgpSignature")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("PublicKeyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PublicKeyId");

                    b.ToTable("FileMapInfos");
                });

            modelBuilder.Entity("PhainonDistributionCenter.Entities.GpgPublicKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("PublicKeys");
                });

            modelBuilder.Entity("PhainonDistributionCenter.Entities.VersionInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Codename")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.ToTable("VersionInfos");
                });

            modelBuilder.Entity("DistributionChannelDistributionInfo", b =>
                {
                    b.HasOne("PhainonDistributionCenter.Entities.DistributionInfo", null)
                        .WithMany()
                        .HasForeignKey("AssociatedDistributionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhainonDistributionCenter.Entities.DistributionChannel", null)
                        .WithMany()
                        .HasForeignKey("ChannelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhainonDistributionCenter.Entities.DistributionInfo", b =>
                {
                    b.HasOne("PhainonDistributionCenter.Entities.VersionInfo", "VersionInfo")
                        .WithMany()
                        .HasForeignKey("VersionInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VersionInfo");
                });

            modelBuilder.Entity("PhainonDistributionCenter.Entities.DistributionSubChannel", b =>
                {
                    b.HasOne("PhainonDistributionCenter.Entities.DistributionInfo", "DistributionInfo")
                        .WithMany("SubChannels")
                        .HasForeignKey("DistributionInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhainonDistributionCenter.Entities.FileMapInfo", "FileMapInfo")
                        .WithMany()
                        .HasForeignKey("FileMapInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DistributionInfo");

                    b.Navigation("FileMapInfo");
                });

            modelBuilder.Entity("PhainonDistributionCenter.Entities.FileMapInfo", b =>
                {
                    b.HasOne("PhainonDistributionCenter.Entities.GpgPublicKey", "PublicKey")
                        .WithMany()
                        .HasForeignKey("PublicKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PublicKey");
                });

            modelBuilder.Entity("PhainonDistributionCenter.Entities.DistributionInfo", b =>
                {
                    b.Navigation("SubChannels");
                });
#pragma warning restore 612, 618
        }
    }
}
